openapi: 3.0.0
info:
  title: Nova Scotia Counties API
  version: 1.0.0
paths:
  /counties:
    get:
      summary: Get a list of counties
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                counties:
                  - name: Halifax
                    population: 480523
                    coordinates:
                      latitude: 44.6488
                      longitude: -63.5752
                  - name: Colchester
                    population: 53178
                    coordinates:
                      latitude: 45.3695
                      longitude: -63.1335
                  - name: Hants
                    population: 44535
                    coordinates:
                      latitude: 45.0708
                      longitude: -64.1869
                  - name: Kings
                    population: 64479
                    coordinates:
                      latitude: 45.0967
                      longitude: -64.7232
                  - name: Lunenburg
                    population: 49770
                    coordinates:
                      latitude: 44.3728
                      longitude: -64.3179
                  - name: Cumberland
                    population: 30803
                    coordinates:
                      latitude: 45.8261
                      longitude: -64.1208
                  - name: Pictou
                    population: 45087
                    coordinates:
                      latitude: 45.8083
                      longitude: -62.5541
                  - name: Annapolis
                    population: 22694
                    coordinates:
                      latitude: 44.5924
                      longitude: -65.4208
                  - name: Queens
                    population: 10589
                    coordinates:
                      latitude: 44.0515
                      longitude: -64.6868
                  - name: Guysborough
                    population: 7463
                    coordinates:
                      latitude: 44.4333
                      longitude: -64.5992
                  - name: Antigonish
                    population: 20629
                    coordinates:
                      latitude: 45.6168
                      longitude: -61.9985
                  - name: Richmond
                    population: 9155
                    coordinates:
                      latitude: 44.6599
                      longitude: -63.5924
                  - name: Inverness
                    population: 17616
                    coordinates:
                      latitude: 45.9561
                      longitude: -61.3096
                  - name: Victoria
                    population: 7147
                    coordinates:
                      latitude: 46.4070
                      longitude: -60.4753
                  - name: Shelburn
                    population: 14032
                    coordinates:
                      latitude: 43.7580
                      longitude: -65.3208
                  - name: Yarmouth
                    population: 25325
                    coordinates:
                      latitude: 43.8374
                      longitude: -66.1173
                  - name: Digby
                    population: 17892
                    coordinates:
                      latitude: 44.6215
                      longitude: -65.7575
